/*
 * generated by Xtext
 */
package tycho.xtext.mwe2.test.lang_a;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class Lang_ARuntimeModule extends tycho.xtext.mwe2.test.lang_a.AbstractLang_ARuntimeModule {

}
