/*
* generated by Xtext
*/
package tycho.xtext.mwe2.test.lang_a;

/**
 * Initialization support for running Xtext languages 
 * without equinox extension registry
 */
public class Lang_AStandaloneSetup extends Lang_AStandaloneSetupGenerated{

	public static void doSetup() {
		new Lang_AStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}

