/*
 * generated by Xtext
 */
package tycho.xtext.mwe2.test.lang_b.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class Lang_BUiModule extends tycho.xtext.mwe2.test.lang_b.ui.AbstractLang_BUiModule {
	public Lang_BUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
