/*
* generated by Xtext
*/
package tycho.xtext.mwe2.test.lang_a.validation;

/**
 * Custom validation rules. 
 *
 * see http://www.eclipse.org/Xtext/documentation.html#validation
 */
public class Lang_AJavaValidator extends tycho.xtext.mwe2.test.lang_a.validation.AbstractLang_AJavaValidator {

//	@Check
//	public void checkGreetingStartsWithCapital(Greeting greeting) {
//		if (!Character.isUpperCase(greeting.getName().charAt(0))) {
//			warning("Name should start with a capital", MyDslPackage.Literals.GREETING__NAME);
//		}
//	}
}
