/*
* generated by Xtext
*/
package tycho.xtext.mwe2.test.lang_b.ui.contentassist;

/**
 * see http://www.eclipse.org/Xtext/documentation.html#contentAssist on how to customize content assistant
 */
public class Lang_BProposalProvider extends tycho.xtext.mwe2.test.lang_b.ui.contentassist.AbstractLang_BProposalProvider {

}
