/*
 * generated by Xtext
 */
package tycho.xtext.mwe2.test.lang_b;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class Lang_BRuntimeModule extends tycho.xtext.mwe2.test.lang_b.AbstractLang_BRuntimeModule {

}
