/*
* generated by Xtext
*/
package tycho.xtext.mwe2.test.lang_b;

/**
 * Initialization support for running Xtext languages 
 * without equinox extension registry
 */
public class Lang_BStandaloneSetup extends Lang_BStandaloneSetupGenerated{

	public static void doSetup() {
		new Lang_BStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}

