/*
 * generated by Xtext
 */
package tycho.xtext.mwe2.test.lang_a.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class Lang_AUiModule extends tycho.xtext.mwe2.test.lang_a.ui.AbstractLang_AUiModule {
	public Lang_AUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
