/*
* generated by Xtext
*/
package tycho.xtext.mwe2.test.lang_a.ui.contentassist;

/**
 * see http://www.eclipse.org/Xtext/documentation.html#contentAssist on how to customize content assistant
 */
public class Lang_AProposalProvider extends tycho.xtext.mwe2.test.lang_a.ui.contentassist.AbstractLang_AProposalProvider {

}
